import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import "./globals.css";


const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "MovieApp",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr" className={roboto.className}>
        <body className="flex flex-col min-h-screen">
        <Header/>
        <main
            className="flex-1 container mx-auto border bg-white rounded-lg py-10 px-4 border-slate-300 drop-shadow-md mt-4">
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
